---
# Docker installation defaults
docker_package: docker-ce
docker_compose_version: "2.20.2"
docker_users: []

# Docker daemon configuration
docker_daemon_options:
  exec-opts: ["native.cgroupdriver=systemd"]
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
    max-file: "3"
  storage-driver: "overlay2"
  metrics-addr: "0.0.0.0:9323"
  experimental: false

# Docker network configuration
docker_network_options:
  bip: "172.17.0.1/16"
  default-address-pools:
    - base: "172.18.0.0/16"
      size: 24

# Docker security options
docker_tls_enabled: true
docker_live_restore: true
docker_userland_proxy: false

# System optimizations
docker_fs_options:
  - fs.inotify.max_user_watches=524288
  - fs.inotify.max_user_instances=512
