---
# NGINX installation and configuration defaults
nginx_package_name: nginx
nginx_service_name: nginx

# Performance settings
nginx_worker_processes: auto
nginx_worker_connections: 2048
nginx_multi_accept: "on"
nginx_worker_rlimit_nofile: 65535

# Buffer settings
nginx_client_body_buffer_size: "128k"
nginx_client_max_body_size: "100M"
nginx_client_body_timeout: "60s"
nginx_client_header_timeout: "60s"

# SSL/TLS configuration
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
nginx_ssl_prefer_server_ciphers: "on"
nginx_ssl_session_cache: "shared:SSL:50m"
nginx_ssl_session_timeout: "1d"
nginx_ssl_session_tickets: "off"
nginx_ssl_stapling: "on"
nginx_ssl_stapling_verify: "on"

# Security headers
nginx_security_headers:
  - "X-Frame-Options SAMEORIGIN"
  - "X-Content-Type-Options nosniff"
  - "X-XSS-Protection \"1; mode=block\""
  - "Referrer-Policy strict-origin-when-cross-origin"
  - "Strict-Transport-Security \"max-age=31536000; includeSubDomains\""

# Logging configuration
nginx_access_log: "/var/log/nginx/access.log"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
