---
- name: restart mongodb
  systemd:
    name: mongod
    state: restarted
    daemon_reload: true

- name: reload mongodb
  systemd:
    name: mongod
    state: reloaded

- name: restart mongodb_exporter
  systemd:
    name: mongodb_exporter
    state: restarted
    daemon_reload: true
  when: mongodb_exporter_enabled
