---
- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true

- name: reload grafana
  systemd:
    name: grafana-server
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
