---
# MongoDB version and installation
mongodb_version: "6.0"
mongodb_package: "mongodb-org"
mongodb_apt_keyserver: "https://www.mongodb.org/static/pgp/server-6.0.asc"
mongodb_apt_repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"

# MongoDB configuration
mongodb_port: 27017
mongodb_bind_ip: "0.0.0.0"
mongodb_auth: true
mongodb_admin_user: "admin"
mongodb_admin_password: "{{ vault_mongodb_admin_password }}"

# System configuration
mongodb_dbpath: "/var/lib/mongodb"
mongodb_logpath: "/var/log/mongodb/mongod.log"
mongodb_pidfile: "/var/run/mongodb/mongod.pid"

# Performance tuning
mongodb_cache_size_gb: 1
mongodb_connection_limit: 1000
mongodb_oplog_size_mb: 1024

# Security configuration
mongodb_authorization: "enabled"
mongodb_ssl: true
mongodb_ssl_cert: "/etc/mongodb/ssl/mongodb.pem"
mongodb_ssl_key: "/etc/mongodb/ssl/mongodb.key"
mongodb_ssl_ca: "/etc/mongodb/ssl/ca.pem"

# Monitoring configuration
mongodb_exporter_enabled: true
mongodb_exporter_port: 9216
mongodb_exporter_version: "0.33.0"

# Backup configuration
mongodb_backup_enabled: true
mongodb_backup_dir: "/var/backups/mongodb"
mongodb_backup_frequency: "daily"
mongodb_backup_retention: 7

# Replication configuration
mongodb_replication_enabled: true
mongodb_replica_set_name: "rs0"
mongodb_replica_members:
  - host: "mongodb1.example.com"
    priority: 1
  - host: "mongodb2.example.com"
    priority: 0.5
  - host: "mongodb3.example.com"
    priority: 0.5

# Sharding configuration
mongodb_sharding_enabled: false
mongodb_config_servers: []
mongodb_shard_servers: []
