---
- name: restart mosquitto
  systemd:
    name: mosquitto
    state: restarted
    daemon_reload: true

- name: reload mosquitto
  systemd:
    name: mosquitto
    state: reloaded

- name: restart mosquitto-exporter
  systemd:
    name: mosquitto-exporter
    state: restarted
    daemon_reload: true
  when: mosquitto_monitoring_enabled
