---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
