---
- name: restart influxdb
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: true

- name: reload influxdb
  systemd:
    name: influxdb
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
