---
- name: restart networking
  service:
    name: networking
    state: restarted

- name: reload sysctl
  command: sysctl -p /etc/sysctl.d/99-network-tuning.conf

- name: reload iptables
  service:
    name: netfilter-persistent
    state: restarted

- name: restart keepalived
  service:
    name: keepalived
    state: restarted

- name: restart netdata
  service:
    name: netdata
    state: restarted
